InterviewTracker/Models/ErrorViewModel.cs
using System;

namespace InterviewTracker.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

InterviewTracker/Controllers/DashboardController.cs
using System;
using System.Threading.Tasks;
using InterviewTracker.BusinessLayer.Services.Repository;
using InterviewTracker.BusinessLayer.ViewModels;
using InterviewTracker.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace InterviewTracker.Controllers
{
    public class DashboardController : Controller
    {
        /// <summary>
        /// Creating Referancce variable of IInterviewTrackerRepository and IUserInterviewTrackerRepository
        /// and injecting Referance into constructor
        /// </summary>
        private readonly IInterviewTrackerRepository _interviewTR;
        private readonly IUserInterviewTrackerRepository _userTR;
        public DashboardController(IInterviewTrackerRepository interviewTrackerRepository, 
            IUserInterviewTrackerRepository userInterviewTrackerRepository )
        {
            _interviewTR = interviewTrackerRepository;
            _userTR = userInterviewTrackerRepository;
        }
        /// <summary>
        /// Get all Interview From InMemory and display on AllInterviewAsync Page
        /// </summary>
        /// <param name="search"></param>
        /// <param name="page"></param>
        /// <returns></returns>
        public async Task<IActionResult> AllInterviewAsync(string search, int page = 1)
        {
            //do code here
            throw new NotImplementedException();
        }
        /// <summary>
        /// Edit Existing Interview to change or reschedule
        /// </summary>
        /// <param name="InterviewId"></param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult EditInterview(int InterviewId)
        {
            //do code here
            throw new NotImplementedException();
        }
        /// <summary>
        /// Post method after edit value is submitted
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> EditInterview(EditInterviewViewModel model)
        {
            //do code here
            throw new NotImplementedException();
        }
        /// <summary>
        /// Delete Interview from InMemory Db by passing ineterviewId
        /// </summary>
        /// <param name="interviewId"></param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult DeleteInterview(int interviewId)
        {
            //do code here
            throw new NotImplementedException();
        }
        /// <summary>
        /// Display confirmation message to delete Interview
        /// </summary>
        /// <param name="interviewId"></param>
        /// <returns></returns>
        [HttpPost, ActionName("DeleteInterview")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteInterviewConfirmed(int interviewId)
        {
            //do code here
            throw new NotImplementedException();
        }
    }
}

InterviewTracker/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using InterviewTracker.Models;

namespace InterviewTracker.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

InterviewTracker/Controllers/InterviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InterviewTracker.BusinessLayer.Services.Repository;
using InterviewTracker.BusinessLayer.ViewModels;
using InterviewTracker.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace InterviewTracker.Controllers
{
    public class InterviewController : Controller
    {
        /// <summary>
        /// Creating Referancce variable of IInterviewTrackerRepository and IUserInterviewTrackerRepository
        /// and injecting Referance into constructor
        /// </summary>
        private readonly IInterviewTrackerRepository _interview;
        private readonly IUserInterviewTrackerRepository _userTR;
        public InterviewController(IInterviewTrackerRepository interviewTrackerRepository, IUserInterviewTrackerRepository userInterviewTrackerRepository)
        {
            _interview = interviewTrackerRepository;
            _userTR = userInterviewTrackerRepository;
        }
        /// <summary>
        /// Add New Interview in InMemorydb
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult AddNewInterview()
        {
            //do code here
            throw new NotImplementedException();
        }
        /// <summary>
        /// Post method of AddNewInterview after AddNewInterview page is added.
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> AddNewInterview(AddInterviewViewModel model)
        {
            //do code here
            throw new NotImplementedException();
        }
    }
}

InterviewTracker/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InterviewTracker.BusinessLayer.Services.Repository;
using InterviewTracker.BusinessLayer.ViewModels;
using InterviewTracker.Entities;
using Microsoft.AspNetCore.Mvc;

namespace InterviewTracker.Controllers
{
    public class UserController : Controller
    {
        /// <summary>
        /// Creating Referancce variable of IInterviewTrackerRepository
        /// and injecting Referance into constructor
        /// </summary>
        private readonly IUserInterviewTrackerRepository _interviewTrackerRepository;
        public UserController(IUserInterviewTrackerRepository interviewTrackerRepository)
        {
            _interviewTrackerRepository = interviewTrackerRepository;
        }
        /// <summary>
        /// Get All User from InMemorydb and display on AllUser
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> AllUser()
        {
            //do code here
            throw new NotImplementedException();
        }
        /// <summary>
        /// Register New User
        /// </summary>
        /// <returns></returns>
        public IActionResult RegisterUser()
        {
            return View();
        }
        /// <summary>
        /// Register new user after post, form fill
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> RegisterUser(RegisterViewModel model)
        {
            //do code here
            throw new NotImplementedException();
        }
        /// <summary>
        /// edit Registred user 
        /// </summary>
        /// <param name="UserId"></param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult EditUser(int UserId)
        {
            //do code here
            throw new NotImplementedException();
        }
        /// <summary>
        /// Edit user after load User on edit mode
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> EditUser(UserEditViewModel model)
        {
            //do code here
            throw new NotImplementedException();
        }
        /// <summary>
        /// Delete User from InMemory Db by passing UserId
        /// </summary>
        /// <param name="UserId"></param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult DeleteUser(int UserId)
        {
            //do code here
            throw new NotImplementedException();
        }
        /// <summary>
        /// Display confirmation message to delete User
        /// </summary>
        /// <param name="UserId"></param>
        /// <returns></returns>
        [HttpPost, ActionName("DeleteUser")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteUserConfirmed(int UserId)
        {
            //do code here
            throw new NotImplementedException();
        }
    }
}

InterviewTracker/Views/Dashboard/AllInterviewAsync.cshtml
@model InterviewTracker.BusinessLayer.ViewModels.InterviewViewModel
@{
    ViewData["Title"] = "AllInterview";
}
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
<div class="card" style="width:100%; margin-top:0px;">
    <div class="card-header bg-success text-white">
        <h3 class="text-center text-uppercase">Admin Dashboard</h3>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <button class="btn btn-primary" onclick="location.href='@Url.Action("AddNewInterview", "Interview")';return false;">Add New Interview</button>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group float-right">
                    Total Interview : @ViewBag.Counts
                </div>
            </div>
        </div>
    </div>
</div>
<p>
    @using (Html.BeginForm("Dashboard", "AllInterviewAsync", FormMethod.Get))
    {
        <b>Search By:</b>
        <text>Interview And Interviewer  Name  : </text> @Html.TextBox("search") <input type="submit" name="submit" value="Search" />
        @Html.ActionLink(" | Back to full List", "AllInterviewAsync", new { @class = "btn btn-primary" })
    }
</p>
<table class="table table-striped">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(m => m.InterviewName)</th>
            <th>@Html.DisplayNameFor(m => m.Interviewer)</th>
            <th>@Html.DisplayNameFor(m => m.InterviewUser)</th>
            <th>@Html.DisplayNameFor(m => m.InterviewDate)</th>
            <th>@Html.DisplayNameFor(m => m.InterviewTime)</th>
            <th>@Html.DisplayNameFor(m => m.InterViewsStatus)</th>
            <th>@Html.DisplayNameFor(m => m.TInterViews)</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.PageCount() == 0)
        {
            <tr>
                <td style="color:red;" colspan="12">
                    Records not found |
                    @Html.ActionLink("Go to all interview", "AllInterviewAsync", new { @class = "btn btn-primary" })
                </td>
            </tr>
        }
        else
        {
            @foreach (var interview in Model.PaginatedInterview())
            {
                <tr>
                    <td>@interview.InterviewName</td>
                    <td>@interview.Interviewer</td>
                    <td>@interview.InterviewUser</td>
                    <td>@interview.InterviewDate.ToShortDateString()</td>
                    <td>@interview.InterviewTime.ToLongTimeString()</td>
                    <td>@interview.InterViewsStatus</td>
                    <td>@interview.TInterViews</td>
                    <td>
                        @Html.ActionLink("Edit", "EditInterview", "Dashboard", new { InterviewId = interview.InterviewId, @class = "btn btn-primary" }) |
                        @Html.ActionLink("Delete", "DeleteInterview", "Dashboard", new { InterviewId = interview.InterviewId, @class = "btn btn-primary" })
                    </td>
                </tr>
            }

        }
    </tbody>
</table>
<ul class="pagination">
    @for (int i = 1; i <= Model.PageCount(); i++)
    {
        <li class="@(i == Model.CurrentPage ? "page-item active" : "page-item")">
            <a class="page-link" href="@Url.Action("AllInterviewAsync", new { page = i })">@i</a>
        </li>
    }
</ul>

InterviewTracker/Views/Dashboard/EditInterview.cshtml
@model InterviewTracker.BusinessLayer.ViewModels.EditInterviewViewModel

@{
    ViewData["Title"] = "Edit Interview";
}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
    $(function () {
        $(".datepicker").datepicker();
    });
</script>

<div class="card" style="width:60%; margin:auto;">
    <div class="card-header bg-success text-white">
        <h5>Update Interview</h5>
    </div>
    <div class="card-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Interviewer)
                        @Html.DropDownListFor(m => m.Interviewer, new SelectList(Model.ApplicationUsers, "FirstName", "FirstName", Model.UserId), new { @class = "form-control", autofocus = "" })

                        @*@Html.TextBoxFor(m => m.Interviewer, new { autofocus = "", @class = "form-control" })*@
                        <span asp-validation-for="Interviewer" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.InterviewName)
                        @Html.TextBoxFor(m => m.InterviewName, new { @class = "form-control" })
                        <span asp-validation-for="InterviewName" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.InterviewUser)
                        @Html.DropDownListFor(m => m.InterviewUser, new SelectList(Model.ApplicationUsers, "FirstName", "FirstName", Model.UserId), new { @class = "form-control" })

                        @*@Html.TextBoxFor(m => m.InterviewUser, new { autofocus = "", @class = "form-control" })*@
                        <span asp-validation-for="InterviewUser" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.UserSkills)
                        @Html.TextBoxFor(m => m.UserSkills, new { @class = "form-control" })
                        <span asp-validation-for="UserSkills" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.InterviewDate)
                        @Html.TextBoxFor(m => m.InterviewDate, "{0:yyy-MM-dd}", new { type = "date", @class = "form-control" })
                        <span asp-validation-for="InterviewDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.InterviewTime)
                        @Html.TextBoxFor(m => m.InterviewTime, "{0:t}", new { type = "time", @class = "form-control" })
                        <span asp-validation-for="InterviewTime" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.InterViewsStatus)
                        <select asp-for="InterViewsStatus" asp-items="Html.GetEnumSelectList<InterviewTracker.Entities.InterviewStatus>()"
                                class="custom-select mr-sm-2 form-control">
                            <option value="">Please Select</option>
                        </select>
                        <span asp-validation-for="InterViewsStatus" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.TInterViews)
                        <select asp-for="TInterViews" asp-items="Html.GetEnumSelectList<InterviewTracker.Entities.TechnicalInterviewStatus>()"
                                class="custom-select mr-sm-2 form-control">
                            <option value="">Please Select</option>
                        </select>
                        <span asp-validation-for="TInterViews" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Remark)
                        @Html.TextAreaFor(m => m.Remark, new { autofocus = "", @class = "form-control" })
                        <span asp-validation-for="Remark" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group text-center">
                <button type="submit" class="btn btn-primary">Save</button>
                <button class="btn btn-danger" onclick="location.href='@Url.Action("AllInterviewAsync", "Dashboard")';return false;">Back To Dashboard</button>
            </div>
        }
    </div>
</div>

InterviewTracker/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

InterviewTracker/Views/Interview/AddNewInterview.cshtml
@model InterviewTracker.BusinessLayer.ViewModels.AddInterviewViewModel

@{
    ViewData["Title"] = "AddNewInterview";
}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
    $(function () {
        $(".datepicker").datepicker();
    });
</script>

<div class="card" style="width:60%; margin:auto;">
    <div class="card-header bg-success text-white">
        <h5>Add New Interview</h5>
    </div>
    <div class="card-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Interviewer)
                        @Html.DropDownListFor(m => m.Interviewer, new SelectList(Model.ApplicationUsers, "FirstName", "FirstName"), "Select Interviewer", new { @class = "form-control" })
                        <span asp-validation-for="Interviewer" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.InterviewName)
                        @Html.TextBoxFor(m => m.InterviewName, new { @class = "form-control" })
                        <span asp-validation-for="InterviewName" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.InterviewUser)
                        @Html.DropDownListFor(m => m.InterviewUser, new SelectList(Model.ApplicationUsers, "FirstName", "FirstName"), "Select Candidate", new { @class = "form-control" })
                        <span asp-validation-for="InterviewUser" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.UserSkills)
                        @Html.TextBoxFor(m => m.UserSkills, new { @class = "form-control" })
                        <span asp-validation-for="UserSkills" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.InterviewDate)
                        @Html.TextBoxFor(m => m.InterviewDate, "{0:d-M-yyyy}", new { type = "date", @class = "form-control" })
                        <span asp-validation-for="InterviewDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.InterviewTime)
                        @Html.TextBoxFor(m => m.InterviewTime, "{0:HH}", new { type = "time", @class = "form-control" })
                        <span asp-validation-for="InterviewTime" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.InterViewsStatus)
                        <select asp-for="InterViewsStatus" asp-items="Html.GetEnumSelectList<InterviewTracker.Entities.InterviewStatus>()"
                                class="custom-select mr-sm-2 form-control">
                            <option value="">Please Select</option>
                        </select>
                        <span asp-validation-for="InterViewsStatus" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.TInterViews)
                        <select asp-for="TInterViews" asp-items="Html.GetEnumSelectList<InterviewTracker.Entities.TechnicalInterviewStatus>()"
                                class="custom-select mr-sm-2 form-control">
                            <option value="">Please Select</option>
                        </select>
                        <span asp-validation-for="TInterViews" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Remark)
                        @Html.TextAreaFor(m => m.Remark, new { autofocus = "", @class = "form-control" })
                        <span asp-validation-for="Remark" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group text-center">
                <button type="submit" class="btn btn-primary">Register</button>
                <button class="btn btn-danger" onclick="location.href='@Url.Action("AllInterviewAsync", "Dashboard")';return false;">Back To Dashboard</button>
            </div>
        }
    </div>
</div>

InterviewTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InterviewTracker</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InterviewTracker</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="AllInterviewAsync">Admin Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="AllUser">All User</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - InterviewTracker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

InterviewTracker/Views/User/AllUser.cshtml
@model IEnumerable<InterviewTracker.Entities.ApplicationUser>
@{
    ViewData["Title"] = "AllUser";
}
<h3 class="text-center text-uppercase">Manage User</h3>
<p>
    <button class="btn btn-primary" onclick="location.href='@Url.Action("RegisterUser", "User")';return false;">Register New User</button>
</p>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(m => m.FirstName)</th>
            <th>@Html.DisplayNameFor(m => m.LastName)</th>
            <th>@Html.DisplayNameFor(m => m.Email)</th>
            <th>@Html.DisplayNameFor(m => m.UserTypes)</th>
            <th>@Html.DisplayNameFor(m => m.Stat)</th>
            <th>@Html.DisplayNameFor(m => m.ReportingTo)</th>
            <th>@Html.DisplayNameFor(m => m.MobileNumber)</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
        <tr>
            <td>@user.FirstName</td>
            <td>@user.LastName</td>
            <td>@user.Email</td>
            <td>@user.UserTypes</td>
            <td>@user.Stat</td>
            <td>@user.ReportingTo</td>
            <td>@user.MobileNumber</td>
            <td>@Html.ActionLink("Edit", "EditUser", "User", new { UserId = user.UserId, @class = "btn btn-primary" }) |
            @Html.ActionLink("Delete", "DeleteUser", "User", new { UserId = user.UserId, @class = "btn btn-primary" })</td>
        </tr>
        }
    </tbody>
</table>